nodeLinker: node-modules

supportedArchitectures:
  os:
    - "current"
    - "linux"
  libc:
    - "current"
    - "musl"

npmPublishRegistry: "https://npm.local"
npmPublishAccess: restricted
npmRegistries:
  //npm.local:
    npmAuthIdent: fransua:password
#httpsCaFilePath:  /usr/local/share/ca-certificates/mkcert_development_CA_28460520527419810000062909674675024658.crt
#enableStrictSsl: false