# This workflow will run specs using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@cmmn'
      - run: npm i
      - run: npm run bootstrap
      - run: npm run ci
      - run: lerna publish from-package -y --no-verify-access --no-push
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
